export const EventTypes = {
  SETTINGS_CHANGED: 'SETTINGS_CHANGED',
  USER_ONBOARDED: 'USER_ONBOARDED',
  WALLET_CREATED: 'WALLET_CREATED',
  WALLET_UPDATED: 'WALLET_UPDATED',
  WALLET_ARCHIVED: 'WALLET_ARCHIVED',
  WALLET_UNARCHIVED: 'WALLET_UNARCHIVED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_ARCHIVED: 'CATEGORY_ARCHIVED',
  MERCHANT_CREATED: 'MERCHANT_CREATED',
  PERSON_CREATED: 'PERSON_CREATED',
  TRANSACTION_CREATED: 'TRANSACTION_CREATED',
  TRANSACTION_UPDATED: 'TRANSACTION_UPDATED',
  TRANSACTION_DELETED: 'TRANSACTION_DELETED',
  BUDGET_THRESHOLD_CROSSED: 'BUDGET_THRESHOLD_CROSSED',
} as const;

export type EventType = (typeof EventTypes)[keyof typeof EventTypes];
